### ISSUE TITLE
MyQTTHub

### ISSUE THREAD

**Issue by ELLISMD65** [parasaurolophus/hubitat-mqtt-connection#1]
Hi, have this sort of working with MyQTTHub, the issue I'm have is, i cant send/receive mqtt messages, i have a connection, and can create a rule to check connection which works. Get error on server when i click disconnect and then connect from from connection driver, messages connection replaced by connection from RemoteAddr, have tried to send a message from Node Red with no joy. Any help much appreciated.Mark

**Comment by parasaurolophus** [comment]
Best guess based on the information you have given would be an authentication issue with your cloud MQTT server. I assume you can successfully connect, send and receive using something like MQTT Explorer?

**Comment by ELLISMD65** [comment]
Hi Kirk Thanks for your email, yes i can connect and send/receive through
Node Red on my Raspberry Pi4 and from a plugin for tasker on my note 10, I
thought it could be the url, when i use node red or tasker i don't use the
prefix, only a guess, I really hope you can fix this as i use MyQTTHub
alot to send messages to node red then to Hubitat. as there's no other
option out there at the moment. Mark

**Comment by parasaurolophus** [comment]
Note that all of this was working as of the time I stopped using Hubitat in my set up. There could have been breaking changes in the Hubitat firmware on which this relies since then.

Assuming that Hubitat's internal MQTT interface still works as it did a few months ago, the URL prefix is required by the MQTT API inside Hubitat. It is simply passed through as is from the device code to the underlying driver. Use "tcp://..." for an unencrypted connection, "ssl://..." to specify the use of encryption as determined by your MQTT broker configuration. I assume you have encryption enabled so would use "ssl://...."

That said, there actually is a better supported alternative to this project. See https://community.hubitat.com/t/beta-mqtt-app-home-assistant-discovery-and-statestream-support/32761 for the public announcement from that other project's developer. I hope that has what you need.

**Comment by ELLISMD65** [comment]
Thanks for your reply, tried it doesn't work for me, I will carry on using
node red to receive messages and a link node to Hubitat. Thanks for your
help.

**Comment by parasaurolophus** [comment]
Could not reproduce
